const en: Record<string, string> = {
  h1: 'Heading 1',
  h2: 'Heading 2',
  h3: 'Heading 3',
  paragraph: 'Normal',
  ol: 'Numbered List',
  ul: 'Bullet List',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  subscript: 'Subscript',
  superscript: 'Superscript',
  textColor: 'Text Color',
  right: 'Align to right',
  left: 'Align to left',
  justify: 'Justify text',
  center: 'Align to center',
  'image.tooltip': 'Image',
  'image.form.header': 'Add an image',
  'image.form.alt': 'Image description',
  'image.form.src': 'Image URL',
  'image.form.submit': 'Add image',
  'table.form.columns': 'Columns',
  'table.form.header': 'Create a new table',
  'table.form.rows': 'Rows',
  'table.form.submit': 'Create table',
  'table.form.includeColumnAsHeaders': 'With column as headers',
  'table.form.includeRowAsHeaders': 'With row as headers',
  'table.menu.insertRowAbv': 'Insert row above',
  'table.menu.insertRowBlv': 'Insert row below',
  'table.menu.insertColLeft': 'Insert column left',
  'table.menu.insertColRight': 'Insert column right',
  'table.menu.makeRowHeader': 'Make row as header',
  'table.menu.removeRowHeader': 'Remove row as header',
  'table.menu.makeColHeader': 'Make col as header',
  'table.menu.removeColHeader': 'Remove col as header',
  'table.menu.deleteCol': 'Delete column',
  'table.menu.deleteRow': 'Delete row',
  'table.menu.deleteTable': 'Delete table',
  'table.tooltip': 'Table',
};

export default en;
