name: Publish HEAD

on:
  workflow_dispatch:

env:
  NODE_VERSION: 24.x
  VITE_BASE_PATH: /react/views/HEAD

jobs:
  publish-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build HEAD
        run: npm run export
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "de2.cheminfo.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJagFXo92FeL12WiCoP9aythZ75qcDrj7sGsy6qHtmCG" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Send build to lactame
        run: |
          rsync -v --archive --delete --human-readable -e "ssh -p 17066" out/ react@de2.cheminfo.org:~/views/HEAD
