name: Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 24.x

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: node
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build release
        env:
          VITE_BASE_PATH: /react/views/${{ needs.release-please.outputs.tag_name }}
        run: npm run export
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "de2.cheminfo.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJagFXo92FeL12WiCoP9aythZ75qcDrj7sGsy6qHtmCG" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Send build to lactame
        run: |
          rsync -v --archive --delete --human-readable -e "ssh -p 17066" out/ react@de2.cheminfo.org:~/views/${{ needs.release-please.outputs.tag_name }}
